version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:5555
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    depends_on:
      - db
