version: '3'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: grupo05
      POSTGRES_PASSWORD: omaewa
    restart: always
    image: postgres
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  app:
    environment:
      DATABASE_URL: postgres://grupo05:omaewa@db/app_db
      REDIS_URL: redis://redis
      DJANGO_MANAGEPY_MIGRATE: "on"
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
      - redis:redis
    ports:
      - "5555:5555"
