---

##################################
## Ansible Playbook para Nginx  ##
##################################


- hosts: [grupo05]
  become: yes
  tasks:
       - name: install EPEL repo.
         yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=present

       - name: install nginx
         yum: name=nginx state=present
~                                       